package zkpcrypto

import (
	"crypto/rand"
	"encoding/json"
	"errors"
	"math/big"
	"os"
	"strings"
	"testing"
)

// randomFieldElement returns a random BN254 field element for testing.
func randomFieldElement(t *testing.T) *big.Int {
	t.Helper()
	for {
		b := make([]byte, 32)
		if _, err := rand.Read(b); err != nil {
			t.Fatalf("rand.Read: %v", err)
		}
		v := new(big.Int).SetBytes(b)
		if IsValidFieldElement(v) {
			return v
		}
	}
}

func TestEncryptDecrypt_Roundtrip(t *testing.T) {
	kp, err := GenerateKeyPair()
	if err != nil {
		t.Fatal(err)
	}

	n := randomFieldElement(t)
	s := randomFieldElement(t)

	enc, err := EncryptSecret(kp.PublicKey, n, s)
	if err != nil {
		t.Fatalf("EncryptSecret: %v", err)
	}

	dec, err := DecryptSecret(enc, kp.PrivateKey)
	if err != nil {
		t.Fatalf("DecryptSecret: %v", err)
	}

	if dec.N.Cmp(n) != 0 {
		t.Errorf("N mismatch: got %s, want %s", dec.N, n)
	}
	if dec.S.Cmp(s) != 0 {
		t.Errorf("S mismatch: got %s, want %s", dec.S, s)
	}
}

func TestEncryptDecrypt_RandomSecrets(t *testing.T) {
	kp, err := GenerateKeyPair()
	if err != nil {
		t.Fatal(err)
	}

	for i := 0; i < 10; i++ {
		n := randomFieldElement(t)
		s := randomFieldElement(t)

		enc, err := EncryptSecret(kp.PublicKey, n, s)
		if err != nil {
			t.Fatalf("[%d] EncryptSecret: %v", i, err)
		}
		dec, err := DecryptSecret(enc, kp.PrivateKey)
		if err != nil {
			t.Fatalf("[%d] DecryptSecret: %v", i, err)
		}
		if dec.N.Cmp(n) != 0 || dec.S.Cmp(s) != 0 {
			t.Errorf("[%d] round-trip mismatch", i)
		}
	}
}

func TestEncryptSecret_WireLength(t *testing.T) {
	kp, _ := GenerateKeyPair()
	n, s := big.NewInt(1), big.NewInt(2)

	enc, err := EncryptSecret(kp.PublicKey, n, s)
	if err != nil {
		t.Fatal(err)
	}

	// 0x + 314 hex chars = 316 total (157 bytes)
	if len(enc) != 316 {
		t.Errorf("wire length = %d, want 316 (0x + 314 hex chars)", len(enc))
	}
	if !strings.HasPrefix(enc, "0x") {
		t.Error("encrypted secret must have 0x prefix")
	}
}

func TestDecryptSecret_WireTooShort(t *testing.T) {
	kp, _ := GenerateKeyPair()
	// 92 bytes = one byte short of minimum (93)
	short := "0x" + strings.Repeat("ab", 92)

	_, err := DecryptSecret(short, kp.PrivateKey)
	if err == nil {
		t.Fatal("expected error for short wire")
	}
	var ce *CryptoError
	if !errors.As(err, &ce) {
		t.Errorf("expected *CryptoError, got %T: %v", err, err)
	}
}

func TestDecryptSecret_BadPubKeyPrefix(t *testing.T) {
	kp, _ := GenerateKeyPair()
	// Build a wire where byte[0] of the ephemeral pub key is 0x02 (compressed prefix).
	wire := make([]byte, 157)
	wire[0] = 0x02 // bad prefix
	badHex := "0x" + strings.ToLower(hexEncode(wire))

	_, err := DecryptSecret(badHex, kp.PrivateKey)
	if err == nil {
		t.Fatal("expected error for bad pubkey prefix")
	}
	var ce *CryptoError
	if !errors.As(err, &ce) {
		t.Errorf("expected *CryptoError, got %T: %v", err, err)
	}
}

func TestDecryptSecret_WrongPrivateKey(t *testing.T) {
	kp1, _ := GenerateKeyPair()
	kp2, _ := GenerateKeyPair()

	enc, err := EncryptSecret(kp1.PublicKey, big.NewInt(42), big.NewInt(99))
	if err != nil {
		t.Fatal(err)
	}

	// Decrypt with the wrong private key — GCM auth should fail.
	_, err = DecryptSecret(enc, kp2.PrivateKey)
	if err == nil {
		t.Fatal("expected error when decrypting with wrong private key")
	}
	var ce *CryptoError
	if !errors.As(err, &ce) {
		t.Errorf("expected *CryptoError, got %T: %v", err, err)
	}
}

func TestDecryptSecret_TamperedCiphertext(t *testing.T) {
	kp, _ := GenerateKeyPair()
	enc, err := EncryptSecret(kp.PublicKey, big.NewInt(1337), big.NewInt(7331))
	if err != nil {
		t.Fatal(err)
	}

	// Flip one byte in the ciphertext region (offset 67 = after ephPubKey(65) + first 2 IV bytes).
	wireBytes, _ := hexDecode(enc[2:])
	wireBytes[90] ^= 0xFF
	tampered := "0x" + hexEncode(wireBytes)

	_, err = DecryptSecret(tampered, kp.PrivateKey)
	if err == nil {
		t.Fatal("expected error for tampered ciphertext")
	}
	var ce *CryptoError
	if !errors.As(err, &ce) {
		t.Errorf("expected *CryptoError, got %T: %v", err, err)
	}
}

func TestEncryptSecret_InvalidPubKey(t *testing.T) {
	// Not 0x04-prefixed
	badPubKey := "0x03" + strings.Repeat("ab", 64)
	_, err := EncryptSecret(badPubKey, big.NewInt(1), big.NewInt(2))
	if err == nil {
		t.Fatal("expected error for non-0x04 public key")
	}
	var ce *CryptoError
	if !errors.As(err, &ce) {
		t.Errorf("expected *CryptoError, got %T: %v", err, err)
	}
}

// TestDecryptSecret_CrossCompat decrypts vectors from crypto/testdata/vectors.json.
// The vectors must be generated by zkp-middleware/internal/crypto/ecies.go to
// confirm byte-for-byte wire-format compatibility.
// This test is skipped if vectors.json contains no vectors.
func TestDecryptSecret_CrossCompat(t *testing.T) {
	type vector struct {
		PrivateKey      string `json:"privateKey"`
		PublicKey       string `json:"publicKey"`
		N               string `json:"n"`
		S               string `json:"s"`
		EncryptedSecret string `json:"encryptedSecret"`
	}
	type file struct {
		Vectors []vector `json:"vectors"`
	}

	data, err := os.ReadFile("testdata/vectors.json")
	if err != nil {
		t.Fatalf("cannot read testdata/vectors.json: %v", err)
	}
	var f file
	if err := json.Unmarshal(data, &f); err != nil {
		t.Fatalf("parse vectors.json: %v", err)
	}
	if len(f.Vectors) == 0 {
		t.Skip("no cross-compat vectors yet — populate testdata/vectors.json with middleware output")
	}

	for i, v := range f.Vectors {
		t.Run(string(rune('0'+i)), func(t *testing.T) {
			dec, err := DecryptSecret(v.EncryptedSecret, v.PrivateKey)
			if err != nil {
				t.Fatalf("DecryptSecret: %v", err)
			}
			wantN, _ := new(big.Int).SetString(v.N, 10)
			wantS, _ := new(big.Int).SetString(v.S, 10)
			if dec.N.Cmp(wantN) != 0 {
				t.Errorf("N mismatch: got %s, want %s", dec.N, wantN)
			}
			if dec.S.Cmp(wantS) != 0 {
				t.Errorf("S mismatch: got %s, want %s", dec.S, wantS)
			}
		})
	}
}

// hexEncode / hexDecode helpers to avoid importing encoding/hex in test body.
func hexEncode(b []byte) string {
	const hx = "0123456789abcdef"
	out := make([]byte, len(b)*2)
	for i, v := range b {
		out[i*2] = hx[v>>4]
		out[i*2+1] = hx[v&0xf]
	}
	return string(out)
}

func hexDecode(s string) ([]byte, error) {
	if len(s)%2 != 0 {
		return nil, nil
	}
	b := make([]byte, len(s)/2)
	for i := 0; i < len(s); i += 2 {
		hi := hexVal(s[i])
		lo := hexVal(s[i+1])
		b[i/2] = (hi << 4) | lo
	}
	return b, nil
}

func hexVal(c byte) byte {
	switch {
	case c >= '0' && c <= '9':
		return c - '0'
	case c >= 'a' && c <= 'f':
		return c - 'a' + 10
	case c >= 'A' && c <= 'F':
		return c - 'A' + 10
	}
	return 0
}
